channels:
- conda-forge
dependencies:
- python=3.9.12
- pip<=22.0.4
- pip:
  - mlflow==3.1.4
  - cloudpickle==3.1.2
  - dill==0.3.8
  - numpy==2.0.2
  - pandas==2.3.3
  - scikit-learn==1.6.1
  - scipy==1.13.1
  - torch==2.8.0
  - transformers==4.57.1
name: mlflow-env
